name: Package

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write
  
on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Create Package
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare files for packaging
      run: |
        mkdir _package_dir
        rsync -av --exclude='.github' --exclude='.git' --exclude='ai-advent-package.tar.gz' ./ _package_dir/
    
    - name: Create package archive
      run: tar -czf ai-advent-package.tar.gz -C _package_dir .

    - name: Create Release
      uses: actions/create-release@v1
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: Automated release from CI/CD pipeline
        draft: false
        prerelease: false
        
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ai-advent-package.tar.gz
        asset_name: ai-advent-package-v${{ github.run_number }}.tar.gz
        asset_content_type: application/gzip
        
